spring.application.name=blogproject
spring.thymeleaf.cache=false
spring.data.mongodb.uri=mongodb://localhost:27017/galeria
spring.data.mongodb.database=galeria
sightengine.api-user=497934805
sightengine.api-secret=4ZWMhrMjcBoExJavMXGSkt6KAxASdwKb
sightengine.api.url=https://api.sightengine.com/1.0/check.json
sightengine.api.models=nudity-2.0,wad,offensive
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

