spring.application.name=blogproject
spring.thymeleaf.cache=false

server.port=${PORT:8080}

spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/galeria}

sightengine.api.user=${SIGHTENGINE_API_USER:}
sightengine.api.secret=${SIGHTENGINE_API_SECRET:}


app.uploads.dir=${APP_UPLOADS_DIR:uploads}

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB